cj.init({require:"loadding,animate,slideshow,inline_pop,debug"});
cj.evt.add(cj.w,"load",function(){navi();cj.slideshow.init("slidshow",{holdtime:5,rolltime:1,tag:"li"});cj.slideshow.init("slideshow_sub",{holdtime:5,rolltime:1,tag:"div"});cj.fn.search_init();cj.w.scrollTo(0,0);if(cj.isIE){var a=cj.d.getElementsByTagName("a");cj.util.each(a,function(a){a.href&&!a.onclick&&(a.onclick=function(){var b=a.getAttribute("target")||"_self";cj.w.open(a.href,b);return!1})})}var d=function(a){a=cj.util.getElmPos(a);a.y-=b.header.offsetHeight||h.header.offsetHeight;cj.animate.scroll_to(a)},
b=cj.util.getElementsByIds("header,wrap");if(b){b.base=cj.w.location.href.replace(cj.w.location.hash,"");cj.evt.add(b.wrap,"click",function(a){a=a||cj.w.event;a=a.target||a.srcElement;if(/a/i.test(a.tagName)){var f=a.getAttribute("href").replace(b.base,"");if(!/#\w+/i.test(f))return!1;cj.util.each(b.wrap.getElementsByTagName("a"),function(a){if(a.name==f.replace("#",""))return d(a),!1})}});var e=/#(\w+)/.exec(cj.w.location.hash);e&&cj.util.each(b.wrap.getElementsByTagName("a"),function(a){if(a.name==
e[1])return d(a),!1})}});
cj.fn={download:function(a){cj.ifr||(cj.ifr=cj.util.addElm(cj.d.body,{tag:"iframe",cssText:"position:absolute;top:-1000px;left:-1000px;display:none",attrib:'frameBorder:0,src:javascript;""'}));cj.ifr.setAttribute("src",a);return!1},search_init:function(){var a=cj.d.getElementById("search");a&&(a.ipt=a.getElementsByTagName("input")[0],a.btn=a.getElementsByTagName("a")[0],a.btn.onclick=function(){cj.w.location="search?q="+encodeURIComponent(a.ipt.value)+"&tabs"},cj.evt.add(a.ipt,"keyup",function(d){d=
d||cj.w.event;if(13==(d.which||d.keyCode))cj.w.location="search?q="+encodeURIComponent(a.ipt.value)+"&tabs"}))}};
function navi(){var a=cj.util.getElementsByIds("navi,navi01,main_arrow,closeBtn"),d=0;a&&(a.active=0,a.container=a.navi01.getElementsByTagName("div")[0],a.h=280,a.w=270,a.main=[],a.sub=[],a.closeBtn.onclick=a.close=function(){cj.util.setStyle(a.main_arrow,{display:"none"});a.container.timer&&clearTimeout(a.container.timer);var b=cj.util.getStyle(a.container,"margin-top")||cj.util.getStyle(a.container,"marginTop")||0;cj.animate.move_to(a.container,"marginTop",0,Math.min(-a.h,parseInt(b,0)),5,20,function(){cj.util.setStyle(a.navi01,
{display:"none"})});a.active=0},cj.evt.add(a.navi,"mouseout",function(b){b=b||cj.w.event;for(b=b.relatedTarget||b.toElement;b;){if(/no_dropdown/i.test(b.className))return a.close(),!1;if(b==a.navi||b==a.navi01)return!1;b=b.offsetParent}a.timer&&clearTimeout(a.timer);a.timer=setTimeout(function(){a.close()},100)}),cj.util.each(a.navi.getElementsByTagName("li"),function(b){/main/i.test(b.className)&&(b.index=d++,b.onclick=function(){var b=this;a.timer&&clearTimeout(a.timer);if(!a.active){a.active=1;
cj.util.setStyle(a.navi01,{display:"block"});cj.util.setStyle(a.main_arrow,{display:"block"});var c=cj.util.getStyle(a.container,"margin-top")||cj.util.getStyle(a.container,"marginTop")||0;cj.animate.move_to(a.container,"marginTop",Math.max(-a.h,parseInt(c,0)),0)}cj.util.setStyle(a.main_arrow,{marginLeft:cj.util.getPos(b).x-cj.util.getPos(a.navi).x+Math.ceil(b.clientWidth/2)-10});cj.util.each(a.sub,function(a){a.active=b.index==a.index;cj.util.setStyle(a,{display:b.index==a.index?"block":"none"})})},
b.getElementsByTagName("a")[0].onmouseover=function(){b.onclick()},a.main.push(b))}),d=0,cj.util.each(a.navi01.getElementsByTagName("ul"),function(b){if(b.parentNode===a.container){b.index=d++;a.sub.push(b);b.hasSubs=[];b.divs=[];var e=0;cj.util.each(b.getElementsByTagName("a"),function(c){cj.util.setStyle(c.parentNode,{paddingTop:5,paddingBottom:5});"nav_nosub"==c.className&&(c.onmouseover=function(){cj.util.each(b.getElementsByTagName("a"),function(a){a.className=a.className.replace(" on","")});
cj.util.each(b.divs,function(a){cj.util.setStyle(a,{display:"none"})})});/nav_sub_arrow|cj_nav_sub/i.test(c.className)&&(c.index=e++,b.hasSubs.push(c),c.onmouseover=c.onclick=function(){var c=this;cj.util.each(b.hasSubs,function(a){a.className=a.index==c.index?a.className+" on":a.className.replace(" on","")});cj.util.each(b.divs,function(b){cj.util.setStyle(b,{width:a.w,overflow:"visible",marginLeft:-50});b.div=b.getElementsByTagName("div")[0];b.ul=b.getElementsByTagName("ul")[0];cj.util.setStyle(b.div,
{overflow:"hidden",marginLeft:50});b.index==c.index?(cj.util.setStyle(b,{display:"block"}),cj.animate.move_to(b.ul,"left",-a.w,0)):(cj.util.setStyle(b,{display:"none"}),cj.util.setStyle(b.ul,{left:-a.w}))})},cj.evt.add(c,"mouseout",function(a){a=a||cj.w.event;for(a=a.relatedTarget||a.toElement;a;){if(a==c||a==b.divs[c.index])return!1;a=a.offsetParent}c.className=c.className.replace(" on","");cj.util.each(b.divs,function(a){cj.util.setStyle(a,{display:"none"})})}))});e=0;cj.util.each(b.getElementsByTagName("div"),
function(a){/navi_sub3_DIV/i.test(a.className)&&(a.index=e++,b.divs.push(a),cj.util.setStyle(a,{display:"none"}))})}}))}
$(function(){$("div.subscription a.unsubscribe").click(function(){var a=/\/(tw|en|jp)\//.exec(window.location.href),d=trim($("div.subscription input").val());if(!isEmail(d))switch(a[1]){case "tw":return alert("\u8acb\u8f38\u5165\u6709\u6548\u7684E-mail"),!1;case "en":return alert("Please enter a valid E-mail"),!1;case "en":return alert("\u6709\u52b9\u306a\u96fb\u5b50\u30e1\u30fc\u30eb\u3092\u5165\u529b\u3057\u3066\u304f\u3060\u3055\u3044"),!1}$.ajax({type:"post",url:"ajax",data:"a=epaper_unsubscribe&email="+
d,success:function(){switch(a[1]){case "tw":return alert("\u53d6\u6d88\u8a02\u95b1\u5b8c\u6210"),!1;case "en":return alert("Unsubscribe completed"),!1;case "en":return alert("\u767b\u9332\u89e3\u9664\u5b8c\u4e86"),!1}$("div.subscription input").val("")}});return!1});$("div.subscription a.subscribe").click(function(){var a=/\/(tw|en|jp)\//.exec(window.location.href),d=trim($("div.subscription input").val());if(!isEmail(d))switch(a[1]){case "tw":return alert("\u8acb\u8f38\u5165\u6709\u6548\u7684E-mail"),
!1;case "en":return alert("Please enter a valid E-mail"),!1;case "en":return alert("\u6709\u52b9\u306a\u96fb\u5b50\u30e1\u30fc\u30eb\u3092\u5165\u529b\u3057\u3066\u304f\u3060\u3055\u3044"),!1}$.ajax({type:"post",url:"ajax",data:"a=epaper_subscribe&email="+d,success:function(){switch(a[1]){case "tw":return alert("\u8a02\u95b1\u5b8c\u6210"),!1;case "en":return alert("subscribe completed"),!1;case "en":return alert("\u6709\u52b9\u306a\u96fb\u5b50\u30e1\u30fc\u30eb\u3092\u5165\u529b\u3057\u3066\u304f\u3060\u3055\u3044"),
alert("\u30b5\u30d6\u30b9\u30af\u30ea\u30d7\u30b7\u30e7\u30f3\u5b8c\u4e86"),!1}$("div.subscription input").val("")}});return!1})});function trim(a){return a.replace(/^\s+|\s+$/g,"")}function isEmail(a){return/^([_a-z0-9-]+)(\.[_a-z0-9-]+)*@([a-z0-9-]+)(\.[a-z0-9-]+)*(\.[a-z]{2,4})$/i.test(a)};
