cj={version:"1.0",modify:"2009/04/17",files:{},elm:[],init:function(a){var c=this,b=navigator,d=b.userAgent;c.d=document;c.w=window;c.b=c.d.documentElement||c.d.body;c.isOpera=c.w.opera&&opera.buildNumber;c.isWebKit=/WebKit/.test(d);c.isIE=!c.isWebKit&&!c.isOpera&&/MSIE/gi.test(d)&&/Explorer/gi.test(b.appName);c.isIE6=c.isIE&&/MSIE [56]/.test(d);c.isIE7=c.isIE&&/MSIE [7]/.test(d);c.isIE8=c.isIE&&/MSIE [8]/.test(d);c.isGecko=!c.isWebKit&&/Gecko/.test(d);c.isMac=-1!=d.indexOf("Mac");c.isAir=/adobeair/i.test(d);
for(var d=document.getElementsByTagName("script"),f=0,e=d.length;f<e;f++)if((b=d[f].src)&&/cj\.js/.test(b)){c.base=b.substring(0,b.lastIndexOf("/"))+"/";break}a&&a.require&&c.util.each(a.require.split(","),function(a){c.files[a]||(c.files[a]=!0,a=c.base+a+".js",c.util.loadJs(a))});c.util.loadCss(c.base+"res/cj.css");c.vp=c.util.getVP()},evt:{guid:1,add:function(a,c,b){if(a.addEventListener)a.addEventListener(c,b,!1);else if(a.attachEvent)a.attachEvent("on"+c,b);else{b.$$guid||(b.$$guid=this.guid++);
a.events||(a.events={});var d=a.events[c];d||(d=a.events[c]={},a["on"+c]&&(d[0]=elme["on"+c]));d[b.$$guid]=b;a["on"+c]=this.handleEvent}return b},remove:function(a,c,b){a.removeEventListener?a.removeEventListener(c,b,!1):a.detachEvent?a.detachEvent("on"+c,b):a.events&&a.events[c]&&delete a.events[c][b.$$guid]},cancel:function(a){a.preventDefault&&a.preventDefault();a.stopPropagation&&a.stopPropagation();try{a.cancelBubble=!0,a.returnValue=!1}catch(c){}}},cookie:{set:function(a,c,b){var d=new Date;
d.setTime(d.getTime()+1E3*b);b="expires="+d.toUTCString();document.cookie=a+"="+c+"; "+b+"; path=/"},get:function(a){var c=RegExp("^"+(a+"=")+"(.*)"),b=null;cj.util.each(document.cookie.split(";"),function(a){a=a.trim();if((a=c.exec(a))&&2==a.length)return b=a[1],!1});return b}},util:{is:function(a,c){return typeof a==c},getMode:function(){if(document.documentMode){var a=document.documentMode;return 8==a?"IE8 Standards Mode":7==a?"IE7 Strict Mode":"IE5 Quirks Mode"}if(document.compatMode)return"CSS1Compat"==
document.compatMode?"Standards":"Quirks"},getMousePos:function(a){return a.pageX&&a.x?{x:a.pageX,y:a.pageY}:{x:a.clientX+this.getScrollPos().x,y:a.clientY+this.getScrollPos().y}},getScrollPos:function(){return{x:document.documentElement.scrollLeft||document.body.scrollLeft,y:document.documentElement.scrollTop||document.body.scrollTop}},getWindowSize:function(){var a=cj.d.documentElement||cj.d.body;return{w:a.scrollWidth,h:a.scrollHeight}},getSize:function(a){var c,b;c=a.style.width;b=a.style.height;
-1===c.indexOf("px")&&(c=0);-1===b.indexOf("px")&&(b=0);return{w:parseInt(c)||a.offsetWidth||a.clientWidth,h:parseInt(b)||a.offsetHeight||a.clientHeight}},getVP:function(){return{x:cj.w.pageXOffset||cj.b.scrollLeft,y:cj.w.pageYOffset||cj.b.scrollTop,w:cj.w.innerWidth||cj.b.clientWidth,h:cj.w.innerHeight||cj.b.clientHeight,ws:{w:cj.b.scrollWidth,h:cj.b.scrollHeight},sp:{x:cj.w.pageXOffset||cj.b.scrollLeft,y:cj.w.pageYOffset||cj.b.scrollTop}}},getElmSize:function(a){return{w:a.clientWidth,h:a.clientHeight}},
getPos:function(a){for(var c=0,b=0;a;){if(a.style.left)return{x:parseInt(a.style.left)||0,y:parseInt(a.style.top)||0};if(a.style.left){c+=parseInt(a.style.left)||0;b+=parseInt(a.style.top)||0;break}else c+=a.offsetLeft,b+=a.offsetTop;a=a.offsetParent}return{x:c,y:b}},getElmPos:function(a){for(var c=y=0;a;)c+=a.offsetLeft,y+=a.offsetTop,a=a.offsetParent;return{x:c,y:y}},getAbsPos:function(a){return{x:parseInt(a.style.left)||0,y:parseInt(a.style.top)||0}},getStyle:function(a,c){return a.currentStyle?
a.currentStyle[c]:cj.w.getComputedStyle?cj.d.defaultView.getComputedStyle(a,null).getPropertyValue(c):x},setStyle:function(a,c){var b=a.style,d;for(d in c)switch(v=c[d],d){case "opacity":this.setOpacity(a,v);break;case "zIndex":b.zIndex=v;break;default:if(cj.util.is(v,"number")||/^[\-0-9\.]+$/.test(v))v+="px";b[d]=v}},fix_ieflash:function(){for(var a=document.getElementsByTagName("object"),c=0;c<a.length;c++)a[c].outerHTML=a[c].outerHTML},loadJs:function(a){if(!cj.files[a]){cj.files[a]=!0;var c=document.getElementsByTagName("head")[0];
o=this.addElm(c,[{tag:"script",attrib:"type:text/javascript;src:"+a}])}},loadCss:function(a){var a=a||"",c=document.getElementsByTagName("head")[0];this.each(a.split(","),function(a){cj.files[a]||(cj.files[a]=!0,cj.util.addElm(c,{tag:"link",attrib:"rel:stylesheet;type:text/css;href:"+a}))})},addElm:function(a,c){var b,d;if(this.is(c,"string")||!c.length)d=a.appendChild(this.createElm(c));else{d=a.appendChild(this.createElm(c[0]));b=1;for(var f=c.length;b<f;b++)this.addElm(d,c[b])}return d},createElm:function(a){var c,
b=document;c=this.is(a,"string")?b.createTextNode(a):b.createElement(a.tag);a.id&&(c.id=a.id,cj.elm[a.id]=c);a.cssText&&(c.style.cssText=a.cssText);a["class"]&&(c.className=a["class"]);a.innerHTML&&(c.innerHTML=a.innerHTML);a.style&&this.setStyle(c,a.style);a.attrib&&cj.util.each(a.attrib.split(";"),function(a){-1!=a.indexOf(":")&&(n=a.indexOf(":"),k=a.substr(0,n).replace(/\s+/g),v=a.substr(n+1,a.length),c.setAttribute(k,v))});return c},removeChild:function(a){try{if(a.firstChild)for(;a.firstChild;)a.firstChild.firstChild?
this.removeChild(a.firstChild):a.removeChild(a.firstChild);a.parentNode.removeChild(a)}catch(c){}},setOpacity:function(a,c){a?0.1>c?a.style.display="none":"undefined"!=typeof a.style.opacity?a.style.opacity=1==c?0.9999999:c:"undefined"!=typeof a.style.MozOpacity?a.style.MozOpacity=1==c?0.9999999:c:"undefined"!=typeof a.style.KhtmlOpacity?a.style.KhtmlOpacity=c:a.style.filter="alpha(opacity="+Math.floor(100*c)+")":alert("setOpacity : o is nto defined")},each:function(a,c,b){if(!a)return 0;b=b||a;if("undefined"!=
typeof a.length)for(var d=0,f=a.length;d<f;d++){if(!1===c.call(b,a[d],d,a))return 0}else for(d in a)if(a.hasOwnProperty(d)&&!1===c.call(b,a[d],d,a))return 0;return 1},ieMask:function(a){var c=a.style,b;b=this.addElm(cj.d.body,{tag:"iframe","class":"cjIEMask",attrib:'frameBorder:0,src:javascript:""'});cj.util.setStyle(b,{width:cj.util.getElmSize(a).w,height:cj.util.getElmSize(a).h,left:c.left,top:c.top,zIndex:c.zIndex-1,opacity:0});a.ieMask=b},winMask:function(a){a.showMask=function(){var a=this.style||
{},b=cj.util.getVP();cj.mask||(cj.mask=cj.util.addElm(cj.d.body,{tag:"div","class":"cjIEMask"}));a.zIndex||(a.zIndex=1E3);cj.util.setStyle(cj.mask,{width:Math.max(b.w,b.ws.w),height:Math.max(b.h,b.ws.h),left:0,top:0,opacity:0.1,visibility:"visible",zIndex:a.zIndex-1});cj.fade.fps=20;cj.fade.start(cj.mask,0.2,0.1,0.6)};a.hideMask=function(){cj.mask&&cj.util.setStyle(cj.mask,{visibility:"hidden",left:-1E4,top:-1E4})}},disableSelect:function(){cj.d.onselectstart||(cj.d.onselectstart=function(){return!1});
cj.d.onmousedown||(cj.d.onmousedown=function(){return!1});cj.w.getSelection&&cj.w.getSelection().removeAllRanges();cj.d.selection&&cj.d.selection.clear&&cj.d.selection.clear()},enableSelect:function(){cj.d.onselectstart&&(cj.d.onselectstart=null);cj.d.onmousedown&&(cj.d.onmousedown=null)},countDown:{init:function(){if(this.n=cj.d.getElementById("cjCountDown"))this.n.sec=this.n.getAttribute("sec"),this.start()},start:function(){this.n.sec=Math.max(1,this.n.sec);this.n.innerHTML=this.n.sec;this.n.sec--;
setTimeout(function(){cj.util.countDown.start()},1E3)}},getElementsByIds:function(a,c){var b={},d=a.split(",");for(i=0;i<d.length;i++)if(!(b[d[i]]=cj.d.getElementById(d[i])))return c&&alert(d[i]+"not found!"),null;b.toString=function(){return a};return b},fixPng:function(){if(cj.isIE6){var a=cj.d.getElementsByTagName("*"),c=/\.png/i;cj.util.each(a,function(a){var d=a.style,f=a.currentStyle,e=f.backgroundImage;if(a.src&&a.src.match(c)&&!d.filter)d.height=a.height,d.width=a.width,d.filter="progid:DXImageTransform.Microsoft.AlphaImageLoader(src='"+
a.src+"',sizingMethod='crop')",a.src="images/blank.gif";else if(e.match(c)){var e=e.split('"'),h="no-repeat"==f.backgroundRepeat?"crop":"scale",g=a.getElementsByTagName("*"),j=g.length;d.filter="progid:DXImageTransform.Microsoft.AlphaImageLoader(src='"+e[1]+"',sizingMethod='"+h+"')";d.height=a.clientHeight+"px";d.backgroundImage="none";if(0!=j){"absolute"!=f.position&&(d.position="static");for(;0<j--;)g[j].style.position||(g[j].style.position="relative")}}})}},releaseSelection:function(){if(cj.d.selection&&
cj.d.selection.empty)try{cj.d.selection.empty()}catch(a){}if(cj.w.getSelection){var c=cj.w.getSelection();c.removeAllRanges&&c.removeAllRanges()}},array_search:function(a,c){for(i in c)if(c[i]==a)return i;return!1},in_array:function(a,c){for(i in c)if(c[i]==a)return!0;return!1}},ajax:{open:function(a){var c=this.getReq();if(c){if(!a.disableLoadding){var b=cj.loadding.newPlayer();b.timer=setTimeout(function(){b.stop();alert("\u9023\u7dda\u903e\u6642\uff0c\u7cfb\u7d71\u66ab\u6642\u7121\u6cd5\u56de\u61c9\u60a8\u7684\u8981\u6c42\u3002\n\u8acb\u91cd\u65b0\u6574\u7406\u7db2\u9801\u5f8c\uff0c\u518d\u8a66\u4e00\u6b21\u3002")},
15E3);b.play()}if(a.onStart)a.onStart();method=a.postData?"POST":"GET";c.open(method,a.URL,!0);c.setRequestHeader("User-Agent","XMLHTTP");a.postData&&c.setRequestHeader("Content-type","application/x-www-form-urlencoded");c.onreadystatechange=function(){if(cj.isIE6)try{"string"==typeof c.responseText&&(setTimeout(function(){if(a.onComplete)a.onComplete(c);a.cb&&a.cb(c)},100),c.onreadystateChange=function(){},a.disableLoadding||(b.stop(),clearTimeout(b.timer)))}catch(d){alert("Connection timeout, please try again")}else if(4===
this.readyState||"undefined"==typeof this.readyState)setTimeout(function(){if(a.onComplete)a.onComplete(c);a.cb&&a.cb(c)},100),c.onreadystateChange=function(){},a.disableLoadding||(b.stop(),clearTimeout(b.timer))};4!=c.readyState&&c.send(a.postData)}},getReq:function(){for(var a=null,c=[function(){return new XMLHttpRequest},function(){return new ActiveXObject("Msxml2.XMLHTTP")},function(){return new ActiveXObject("Msxml3.XMLHTTP")},function(){return new ActiveXObject("Microsoft.XMLHTTP")}],b=0;b<
c.length;b++){try{a=c[b]()}catch(d){continue}break}return a}},drag:function(a,c){var c=c||cj.w.event,b=this,d=cj.d.documentElement||b.d.body,f,e,h,g,j;e=b.util.getVP();e.w-=2;e.h-=2;f=b.util.getSize(d);f.w=Math.max(e.w,f.w);f.h=Math.max(e.h,f.h);h=b.util.getMousePos(c);g=b.util.getElmPos(a);j=b.util.getSize(a);f=b.isIE6?"iframe":"div";b.bodyMask||(b.bodyMask=cj.util.addElm(b.d.body,{tag:f,"class":"cjBodyMask",style:{opacity:0.5}}));b.util.setStyle(b.bodyMask,{width:e.w+"px",height:e.h+"px",zIndex:parseInt(a.style.zIndex)-
100,display:"block"});a.cp||(a.cp=cj.util.addElm(b.d.body,{tag:f,"class":"cjMoveMask",style:{opacity:0.5}}));b.util.setStyle(a.cp,{width:a.style.width,height:a.style.height,left:a.style.left,top:a.style.top,zIndex:parseInt(a.style.zIndex)+1,display:"block"});b.util.disableSelect();mu=b.evt.add(cj.d,"mouseup",function(){b.util.enableSelect();b.evt.remove(cj.d,"mouseup",mu);b.evt.remove(cj.d,"mousemove",mm);b.util.setStyle(a,{width:a.cp.style.width,height:a.cp.style.height,left:a.cp.style.left,top:a.cp.style.top});
a.cp.style.display="none";a.blur();try{b.bodyMask.focus()}catch(e){}b.bodyMask.style.display="none";d.style.overflow="auto";b.evt.cancel(c);cj.util.releaseSelection()});mm=b.evt.add(b.d,"mousemove",function(c){var d=dy=0,c=c||cj.w.event,f=cj.util.getMousePos(c),d=f.x-h.x;dy=f.y-h.y;d=Math.max(d,e.x-g.x);d=Math.min(d,e.x+e.w-g.x-j.w);dy=Math.max(dy,e.y-g.y);dy=Math.min(dy,e.y+e.h-g.y-j.h);0!=d+dy&&(a.cp.style.left=g.x+d+"px",a.cp.style.top=g.y+dy+"px");b.evt.cancel(c)});b.evt.cancel(c)},fade:{fps:10,
start:function(a,c,b,d){a.steps=(d-b)/(c*this.fps);a.timer=null;this.dofade(a,b,d)},dofade:function(a,c,b){var d;d=0<a.steps;c+=a.steps;cj.util.setOpacity(a,c);d^0<c-b?a.timer=setTimeout(function(){cj.fade.dofade(a,c,b)},1E3/this.fps):(clearTimeout(a.timer),a.timer=null)}},popMsg:{div:null,move:10,timer:null,holdTime:3E3,init:function(a,c,b,d){var f=cj.util.getVP();this.size=b||{w:100,h:20};d&&(this.holdTime=1E3*d);this.clear();c.x=Math.min(f.ws.w-this.size.w-20,c.x);this.div=cj.util.addElm(cj.d.body,
{tag:"div","class":"cjPopMsg",innerHTML:a,style:{left:c.x,top:c.y}});this.show()},show:function(a){var c,b,a=a||1;this.div.offsetWidth<this.size.w?(c=Math.abs(this.size.w/this.move*a),b=Math.abs(this.size.h/this.move*a),cj.util.setStyle(this.div,{width:c,height:b}),this.timer=setTimeout(function(){cj.popMsg.show(++a)},1)):this.timer=setTimeout(function(){cj.popMsg.clear()},this.holdTime)},clear:function(){this.div&&(clearTimeout(this.timer),this.timer=null,cj.d.body.removeChild(this.div),this.div=
null)}},form:{popMsgSize:{w:100,h:16},chk:function(a,c){if(!a)return!1;if("undefined"==typeof a.lang||!a.lang)return alert("lang not set"),!1;for(var b=a.lang.value,d=0;d<c.length;d++){var f=c[d].split(","),e=a[f[0]];if(!e)return alert(f[0]+" not set"),!1;var h=f[1];if(!h)return alert(f[1]+" not set"),!1;var g=e.getAttribute("title");if(!g)return alert(f[0]+" title not set"),!1;f=cj.util.getElmPos(e);0==f.x||0==f.y?(cj.util.getVP(),e.nextSibling&&(f=cj.util.getElmPos(e.nextSibling.parentNode),f.x+=
e.nextSibling.parentNode.offsetWidth)):f.x+=e.offsetWidth;switch(h){case "num":if(e.value=cj.form.trim(e.value),!cj.form.isNumber(e.value))return e.focus(),cj.popMsg.init(g+cj.form.msg.not_number[b],f,cj.form.popMsgSize,3),!1;case "text":if(""==e.value){try{e.focus()}catch(j){}"hidden"==e.type&&cj.w.scrollTo(f.x,f.y);cj.popMsg.init(g+cj.form.msg.not_null[b],f,cj.form.popMsgSize,3);return!1}break;case "date":if(!cj.form.isDate(e.value))return e.focus(),cj.popMsg.init(g+cj.form.msg.not_null[b],f,cj.form.popMsgSize,
3),!1;break;case "email":if(!cj.form.isEmail(e.value))return e.focus(),cj.popMsg.init(cj.form.msg.valid[b]+g,f,cj.form.popMsgSize,3),!1;break;case "account":if(!cj.form.isAccount(e.value))return e.focus(),cj.popMsg.init(cj.form.msg.valid[b]+g,f,cj.form.popMsgSize,3),!1;break;case "password":if(!cj.form.isPasswd(e.value))return e.focus(),cj.popMsg.init(cj.form.msg.valid[b]+g,f,cj.form.popMsgSize,3),!1;if(e.getAttribute("confirm")&&(g=a[e.getAttribute("confirm")])&&e.value!=g.value)return g.focus(),
cj.popMsg.init(g.getAttribute("msg"),f,cj.form.popMsgSize,3),!1;break;case "checkbox":e.v="";e.last=null;cj.util.each(e.parentNode.getElementsByTagName("input"),function(a){/checkbox/i.test(a.type)&&(a.checked&&(e.v+=a.value+","),e.last=a)});e.value=e.v.replace(/,$/,"");if(!e.value){try{e.focus()}catch(l){}f=cj.util.getElmPos(e.last);f.x+=30;cj.popMsg.init(e.getAttribute("title"),f,cj.form.popMsgSize,3);return!1}break;case "creditCard":h=document.getElementById(e.getAttribute("cardName"));if(!h)return alert("Attribute : cardName not set"),
!1;if(!cj.form.checkCreditCard.check(h.value,e.value))return e.focus(),cj.popMsg.init(cj.form.msg.valid[b]+g,f,cj.form.popMsgSize,3),!1;break;case "sid":if(!cj.form.isSid(e.value))return e.focus(),cj.popMsg.init(cj.form.msg.valid[b]+g,f,cj.form.popMsgSize,3),!1}}return!0},isEmail:function(a){return/^([_a-z0-9-]+)(\.[_a-z0-9-]+)*@([a-z0-9-]+)(\.[a-z0-9-]+)*(\.[a-z]{2,4})$/i.test(a)},isAccount:function(a){return/[^a-z^A-Z^0-9^\.]/.test(a)?!1:/[a-zA-Z0-9\.]{6,30}/.test(a)},isPasswd:function(a){return/.{6,30}/.test(a)},
isNumber:function(a){return/^\d+\.?\d*$/.exec(a)},isSid:function(a){code=[10,11,12,13,14,15,16,17,34,18,19,20,21,22,35,23,24,25,26,27,28,29,0,30,31,0];a=a.toLowerCase();if(10!=a.length)return!1;re=/[a-z]/;if(!a.charAt(0).match(re))return!1;re=/[0-9]/;for(i=1;10>i;i++)if(!a.charAt(i).match(re))return!1;id0=code[a.charAt(0).charCodeAt(0)-97];return!id0?!1:!((10-a.charAt(9)-(Math.floor(id0/10)+9*(id0%10)+8*a.charAt(1)+7*a.charAt(2)+6*a.charAt(3)+5*a.charAt(4)+4*a.charAt(5)+3*a.charAt(6)+2*a.charAt(7)+
1*a.charAt(8))%10)%10)},isDate:function(a){return/\d{4}[\/-]\d{2}[[\/-]\d{2}/.text(a)},trim:function(a){return a.replace(/^\s+|\s+$/g,"")},chk_url:function(a){a=cj.form.trim(a);return!a||/^https?:\/\/$/.test(a)?"":/^https?:\/\//i.test(a)?a:"http://"+a},init:function(){cj.evt.add(cj.d,"keyup",function(a){var a=a||cj.w.event,c=a.srcElement||a.target;if(/input/i.test(c.tagName))if(/cj_tel/i.test(c.className)&&(c.value=c.value.replace(/[^0-9+-_\s]/g,"")),/cj_numbers/i.test(c.className))c.value=c.value.replace(/[^0-9-]/g,
"");else if(/cj_integer/i.test(c.className))c.value=parseInt(c.value,10)||"";else if(m=/cj_float(\d)?/i.exec(c.className)){c.value=c.value.replace(/[^-^0-9\.]/g,"");var b=c.value;c.timer&&clearTimeout(c.timer);c.timer=setTimeout(function(){b=parseFloat(b,10)||0;m[1]&&(b=b.toFixed(m[1]));c.value=b.toString().replace(/\.?0+$/,"")},2E3);c.running=0}else/cj_azd/i.test(c.className)&&(c.value=c.value.replace(/[^a-zA-Z0-9]/g,""))})},radio:function(a){if(a){a.options=[];a.checkedIndex=-1;var c=0;a.ipt=a.parentNode.getElementsByTagName("input");
cj.util.each(a.ipt,function(b){/radio/i.test(b.type)&&(b.index=c++,b.tg=a,b.onclick=function(){this.checked&&(this.tg.value=this.value,this.tg.checkedIndex=this.index)},a.value==b.value&&(b.checked=!0,a.checkedIndex=b.index),a.options.push(b))});a.onchange=function(){cj.util.each(a.ipt,function(b){b.checked=b.value==a.value?!0:!1})}}},checkbox:function(a){a.v=a.value.split(",");a.ipt=[];cj.util.each(a.parentNode.getElementsByTagName("input"),function(c){a!=c&&(a.ipt.push(c),c.tg=a,c.checked=cj.util.in_array(c.value,
a.v),c.onclick=function(){var a=this;a.tg.value="";cj.util.each(a.tg.ipt,function(c){c.checked&&(a.tg.value+=c.value+",")});a.tg.value=a.tg.value.replace(/,*$/,"")})})},select:function(a){a.data_value=a.getAttribute("data-value");for(var c=a.options.length,b=0;b<c;b++)if(a.options[b].value==a.data_value){a.selectedIndex=b;break}},msg:{not_null:{tw:" \u5fc5\u586b ",en:" is required! "},valid:{tw:" \u8acb\u8f38\u5165\u6709\u6548\u7684 ",en:" Please specify valid "},day:{tw:"\u65e5\u671f",en:"Date"},
not_number:{tw:" \u4e0d\u662f\u6578\u5b57 ",en:" is not number"}},taMax:function(a,c,b){b=b||0;a.note=cj.util.createElm({tag:"div",cssText:"font:normal 12px verdana; width:80px; text-align:center; border:1px solid #f9f; margin:0; padding:5px"});a.parentNode.insertBefore(a.note,a);a.len=a.value.replace(/\s/g,"").length;a.note.innerHTML=a.len.toString()+" / "+c;a.note.style.color=a.len<=c?"#333":"#f3f";a.check=function(){if(!a.running){a.running=1;a.len=a.value.replace(/\s/g,"").length;if(b){for(var d=
0,f=a.value.length;a.len>c;)if(a.value=a.value.replace(/(\w$|\W$|\n\r$|\r\n$|\n$|\$r$)/,""),a.len=a.value.replace(/\s/g,"").length,d++>f){a.running=0;break}a.len=a.value.replace(/\s/g,"").length}a.note.style.color=a.len<=c?"#333":"#f3f";a.note.innerHTML=a.len.toString()+" / "+c;a.running=0}};cj.evt.add(a,"keyup",a.check);cj.evt.add(a,"paste",function(){setTimeout(a.check,100)});cj.evt.add(a,"keydown",function(b){if(a.len>=c)switch(b=b||cj.w.event,b.keyCode||b.which){case 8:case 13:case 17:case 35:case 36:case 37:case 38:case 39:case 40:case 46:case 88:break;
default:cj.evt.cancel(b)}})}},updateUid:function(a){cj.uid_timer&&clearTimeout(cj.uid_timer);a=a||{u:"ajax",uid:0,cb:null};a.u=a.u||"ajax";a.uid=a.uid||cj.uid||1;postData="a=updateUid&uid="+a.uid;cj.ajax.open({URL:a.u,postData:postData,disableLoadding:1,cb:function(c){debug&&cj.debug.log.add(c.responseText);try{r=eval(c.responseText),r.uid&&(cj.uid=r.uid,cj.uid_timer=setTimeout(function(){cj.updateUid({u:a.u,uid:cj.uid})},12E5),a.cb&&a.cb())}catch(b){}}})},flashObj:{init:function(a){this.src=a.src;
this.width=a.w;this.height=a.h;this.version="7,0,14,0";this.flashVars=this.id=null;this.params=a.params.split(",")||[];return this},setVersion:function(a){this.version=a},setId:function(a){this.id=a},setBgcolor:function(a){this.bgcolor=a},setFlashvars:function(a){this.flashVars=a},toString:function(){var a=new String;if(cj.isIE){a+='<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" ';null!=this.id&&(a+='id="'+this.id+'" ');for(var a=a+('codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version='+
this.version+'" '),a=a+('width="'+this.width+'" '),a=a+('height="'+this.height+'" />'),a=a+('<param name="movie" value="'+this.src+'" />'),a=a+'<param name="quality" value="high" /><param name="wmode" value="transparent" />',c=0;c<this.params.length/2;c++)a+='<param name="'+this.params[2*c]+'" value="'+this.params[2*c+1]+'" />';null!=this.flashVars&&(a+='<param name="flashvars" value="'+this.flashVars+'" />');a+="</object>"}else{allowfullscreen="true";a+='<embed src="'+this.src+'" ';null!=this.id&&
(a+='name="'+this.id+'" ');a+='quality="high" wmode="transparent" ';a+='width="'+this.width+'" ';a+='height="'+this.height+'" ';a+='type="application/x-shockwave-flash" ';for(c=0;c<this.params.length/2;c++)a+=this.params[2*c]+'="'+this.params[2*c+1]+'" ';null!=this.flashVars&&(a+='flashvars="'+this.flashVars+'" ');a+='pluginspage="http://www.macromedia.com/go/getflashplayer">';a+="</embed>"}return a},write:function(a){a&&this.init(a);cj.d.write(this.toString())}}};
Function.prototype.clone=function(){var a=this,c=function(){return a.apply(this,arguments)};c.prototype=a.prototype;for(property in a)a.hasOwnProperty(property)&&"prototype"!==property&&(c[property]=a[property]);return c};function html_entity_decode(a,c){var b={},d="",f="",e="",f=a.toString();if(!1===(b=this.get_html_translation_table("HTML_ENTITIES",c)))return!1;delete b["&"];b["&"]="&amp;";for(d in b)e=b[d],f=f.split(e).join(d);return f=f.split("&#039;").join("'")}
function get_html_translation_table(a,c){var b={},d={},f=0,e="",e={},h={},g={},j={};e[0]="HTML_SPECIALCHARS";e[1]="HTML_ENTITIES";h[0]="ENT_NOQUOTES";h[2]="ENT_COMPAT";h[3]="ENT_QUOTES";g=!isNaN(a)?e[a]:a?a.toUpperCase():"HTML_SPECIALCHARS";j=!isNaN(c)?h[c]:c?c.toUpperCase():"ENT_COMPAT";if("HTML_SPECIALCHARS"!==g&&"HTML_ENTITIES"!==g)throw Error("Table: "+g+" not supported");b["38"]="&amp;";"HTML_ENTITIES"===g&&(b["160"]="&nbsp;",b["161"]="&iexcl;",b["162"]="&cent;",b["163"]="&pound;",b["164"]="&curren;",
b["165"]="&yen;",b["166"]="&brvbar;",b["167"]="&sect;",b["168"]="&uml;",b["169"]="&copy;",b["170"]="&ordf;",b["171"]="&laquo;",b["172"]="&not;",b["173"]="&shy;",b["174"]="&reg;",b["175"]="&macr;",b["176"]="&deg;",b["177"]="&plusmn;",b["178"]="&sup2;",b["179"]="&sup3;",b["180"]="&acute;",b["181"]="&micro;",b["182"]="&para;",b["183"]="&middot;",b["184"]="&cedil;",b["185"]="&sup1;",b["186"]="&ordm;",b["187"]="&raquo;",b["188"]="&frac14;",b["189"]="&frac12;",b["190"]="&frac34;",b["191"]="&iquest;",b["192"]=
"&Agrave;",b["193"]="&Aacute;",b["194"]="&Acirc;",b["195"]="&Atilde;",b["196"]="&Auml;",b["197"]="&Aring;",b["198"]="&AElig;",b["199"]="&Ccedil;",b["200"]="&Egrave;",b["201"]="&Eacute;",b["202"]="&Ecirc;",b["203"]="&Euml;",b["204"]="&Igrave;",b["205"]="&Iacute;",b["206"]="&Icirc;",b["207"]="&Iuml;",b["208"]="&ETH;",b["209"]="&Ntilde;",b["210"]="&Ograve;",b["211"]="&Oacute;",b["212"]="&Ocirc;",b["213"]="&Otilde;",b["214"]="&Ouml;",b["215"]="&times;",b["216"]="&Oslash;",b["217"]="&Ugrave;",b["218"]=
"&Uacute;",b["219"]="&Ucirc;",b["220"]="&Uuml;",b["221"]="&Yacute;",b["222"]="&THORN;",b["223"]="&szlig;",b["224"]="&agrave;",b["225"]="&aacute;",b["226"]="&acirc;",b["227"]="&atilde;",b["228"]="&auml;",b["229"]="&aring;",b["230"]="&aelig;",b["231"]="&ccedil;",b["232"]="&egrave;",b["233"]="&eacute;",b["234"]="&ecirc;",b["235"]="&euml;",b["236"]="&igrave;",b["237"]="&iacute;",b["238"]="&icirc;",b["239"]="&iuml;",b["240"]="&eth;",b["241"]="&ntilde;",b["242"]="&ograve;",b["243"]="&oacute;",b["244"]=
"&ocirc;",b["245"]="&otilde;",b["246"]="&ouml;",b["247"]="&divide;",b["248"]="&oslash;",b["249"]="&ugrave;",b["250"]="&uacute;",b["251"]="&ucirc;",b["252"]="&uuml;",b["253"]="&yacute;",b["254"]="&thorn;",b["255"]="&yuml;");"ENT_NOQUOTES"!==j&&(b["34"]="&quot;");"ENT_QUOTES"===j&&(b["39"]="&#39;");b["60"]="&lt;";b["62"]="&gt;";for(f in b)e=String.fromCharCode(f),d[e]=b[f];return d}
cj.animate={move_to:function(a,c,b,d,f){function e(){a.timer&&clearTimeout(a.timer);Math.abs(d-h)<=f?a.style[c]=d+"px":(h+=Math.floor((d-h)/f),a.style[c]=h+"px",a.timer=setTimeout(function(){e()},g))}var h=0,f=f||5,g=g||20;e()}};
